### ISSUE TITLE
Was this successfully developed?

### ISSUE THREAD

**Issue by spencerthayer** [Legac3e/DSU-Final-Project#1]
Was this successfully developed?

**Comment by Legac3e** [comment]
Yep, it was! We completed all of the features we wanted. It's a shopping list app, and we wanted to be able to have the user add any store they wanted, and within each store to have it separated by "sections" (meat, ingredients, fruits/veggies, clothes etc.) and gave the user the ability to add or remove as many sections as they wished, and then to have items attached to the sections, and have the user add or remove as many items as they wish from each section. All while having the data be persistent through the browser as well as from a database (we used mongoDB). (So if they didn't connect to the database it would keep everything they had in the past as cache. And upon connecting to the database it would pull from it if it was newer). This was just the final (group) project for an over the summer camp, which was hosted by Dixie State University. We used React and mongoose primarily, with some html, css and jQuery as well to achieve the finished look. :) Let me know if you have any further questions!

**Comment by Legac3e** [comment]
Oh, and my mistake I forgot that I never merged over the project to my github profile, this is the repo with the finished product: https://github.com/MaxSinbraith/Shopr

This one right here was my first idea to create an anonymous forum but decided to join another group to build a shopping list app.
